spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_net_db
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date: MM/dd/yyyy
      date-time: MM/dd/yyyy HH:mm:ss
app:
  image:
    folder: resources